name: Publish Docker image

on:
  push:
    tags:
      - '*'

jobs:
  publish-docker:

    runs-on: ubuntu-latest

    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3@v3.3.0
        with:
          # list of Docker images to use as base name for tags
          images: |
            expediagroup/mittens
          # Generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=tag

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
