name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  build:
    name: Build and run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21
    - name: Check out code
      uses: actions/checkout@v4
    - name: Build
      run: make test

